import MRD1 from "../assets/images/mrd.jpg";
import MRD2 from "../assets/images/mrd1.png";
import MUD from "../assets/images/mud.png";
import MEN from "../assets/images/enm.jpg";
import MEN1 from "../assets/images/enm1.jpg";
import MWS from "../assets/images/mws.jpg";
import CWC from "../assets/images/cwc.jpg";
import CGWB from "../assets/images/cgwb.jpg";
import CPCB from "../assets/images/cpcb.png";
import NDMA from "../assets/images/ndma.png";
import MHA from "../assets/images/mha.png";
import NDRF from "../assets/images/ndr.jpg";

const Departments = [
  {
    name: "Ward A",
    url: MRD2,
    desc: "It is responsible for managing various local services and infrastructure within its jurisdiction, such as sanitation, water supply, waste management, roads, etc. It may have its own designated officials and local government representatives who oversee the day-to-day operations and address the needs of the residents in that specific area.",
    name1: "Ward B",
    url1: MUD,
    desc1:
      "It is responsible for managing various local services and infrastructure within its jurisdiction, such as sanitation, water supply, waste management, roads, etc. It may have its own designated officials and local government representatives who oversee the day-to-day operations and address the needs of the residents in that specific area.",
  },
  {
    name: "Ward C",
    url: MEN1,
    desc: "It is responsible for managing various local services and infrastructure within its jurisdiction, such as sanitation, water supply, waste management, roads, etc. It may have its own designated officials and local government representatives who oversee the day-to-day operations and address the needs of the residents in that specific area.",
    name1: "Ward D",
    url1: MWS,
    desc1:
      "It is responsible for managing various local services and infrastructure within its jurisdiction, such as sanitation, water supply, waste management, roads, etc. It may have its own designated officials and local government representatives who oversee the day-to-day operations and address the needs of the residents in that specific area.",
  },
  {
    name: "Ward E",
    url: CWC,
    desc: "It is responsible for managing various local services and infrastructure within its jurisdiction, such as sanitation, water supply, waste management, roads, etc. It may have its own designated officials and local government representatives who oversee the day-to-day operations and address the needs of the residents in that specific area.",
    name1: "Ward F north",
    url1: CGWB,
    desc1:
      "It is responsible for managing various local services and infrastructure within its jurisdiction, such as sanitation, water supply, waste management, roads, etc. It may have its own designated officials and local government representatives who oversee the day-to-day operations and address the needs of the residents in that specific area.",
  },
  {
    name: "Ward F south",
    url: CPCB,
    desc: "It is responsible for managing various local services and infrastructure within its jurisdiction, such as sanitation, water supply, waste management, roads, etc. It may have its own designated officials and local government representatives who oversee the day-to-day operations and address the needs of the residents in that specific area.",
    name1: "Ward G north ",
    url1: NDMA,
    desc1:
      "It is responsible for managing various local services and infrastructure within its jurisdiction, such as sanitation, water supply, waste management, roads, etc. It may have its own designated officials and local government representatives who oversee the day-to-day operations and address the needs of the residents in that specific area.",
  },
  {
    name: "Ward G south",
    url: MHA,
    desc: "It is responsible for managing various local services and infrastructure within its jurisdiction, such as sanitation, water supply, waste management, roads, etc. It may have its own designated officials and local government representatives who oversee the day-to-day operations and address the needs of the residents in that specific area.",
    name1: "Ward H east",
    url1: NDRF,
    desc1:
      "It is responsible for managing various local services and infrastructure within its jurisdiction, such as sanitation, water supply, waste management, roads, etc. It may have its own designated officials and local government representatives who oversee the day-to-day operations and address the needs of the residents in that specific area.",
  },
  {
    name: "Ward H west",
    url: MHA,
    desc: "It is responsible for managing various local services and infrastructure within its jurisdiction, such as sanitation, water supply, waste management, roads, etc. It may have its own designated officials and local government representatives who oversee the day-to-day operations and address the needs of the residents in that specific area.",
    name1: "Ward K east",
    url1: NDRF,
    desc1:
      "It is responsible for managing various local services and infrastructure within its jurisdiction, such as sanitation, water supply, waste management, roads, etc. It may have its own designated officials and local government representatives who oversee the day-to-day operations and address the needs of the residents in that specific area.",
  },
  {
    name: "Ward K west",
    url: MHA,
    desc: "It is responsible for managing various local services and infrastructure within its jurisdiction, such as sanitation, water supply, waste management, roads, etc. It may have its own designated officials and local government representatives who oversee the day-to-day operations and address the needs of the residents in that specific area.",
    name1: "Ward M east",
    url1: NDRF,
    desc1:
      "It is responsible for managing various local services and infrastructure within its jurisdiction, such as sanitation, water supply, waste management, roads, etc. It may have its own designated officials and local government representatives who oversee the day-to-day operations and address the needs of the residents in that specific area.",
  },
  {
    name: "Ward M west ",
    url: MHA,
    desc: "It is responsible for managing various local services and infrastructure within its jurisdiction, such as sanitation, water supply, waste management, roads, etc. It may have its own designated officials and local government representatives who oversee the day-to-day operations and address the needs of the residents in that specific area.",
    name1: "Ward L",
    url1: NDRF,
    desc1:
      "It is responsible for managing various local services and infrastructure within its jurisdiction, such as sanitation, water supply, waste management, roads, etc. It may have its own designated officials and local government representatives who oversee the day-to-day operations and address the needs of the residents in that specific area.",
  },
  {
    name: "Ward T",
    url: MHA,
    desc: "It is responsible for managing various local services and infrastructure within its jurisdiction, such as sanitation, water supply, waste management, roads, etc. It may have its own designated officials and local government representatives who oversee the day-to-day operations and address the needs of the residents in that specific area.",
    name1: "Ward N",
    url1: NDRF,
    desc1:
      "It is responsible for managing various local services and infrastructure within its jurisdiction, such as sanitation, water supply, waste management, roads, etc. It may have its own designated officials and local government representatives who oversee the day-to-day operations and address the needs of the residents in that specific area.",
  },
];
const States = [
  { value: "1", name: "Andhra Pradesh" },
  { value: "2", name: "Arunachal Pradesh" },
  { value: "3", name: "Assam" },
  { value: "4", name: "Bihar" },
  { value: "5", name: "Chhattisgarh" },
  { value: "6", name: "Goa" },
  { value: "7", name: "Gujarat" },
  { value: "8", name: "Haryana" },
  { value: "9", name: "Himachal Pradesh" },
  { value: "10", name: "Jharkhand" },
  { value: "11", name: "Karnataka" },
  { value: "12", name: "Kerala" },
  { value: "13", name: "Madhya Pradesh" },
  { value: "14", name: "Maharashtra" },
  { value: "15", name: "Manipur" },
  { value: "16", name: "Meghalaya" },
  { value: "17", name: "Mizoram" },
  { value: "18", name: "Nagaland" },
  { value: "19", name: "Odisha" },
  { value: "20", name: "Punjab" },
  { value: "21", name: "Rajasthan" },
  { value: "22", name: "Sikkim" },
  { value: "23", name: "Tamil Nadu" },
  { value: "24", name: "Telangana" },
  { value: "25", name: "Tripura" },
  { value: "26", name: "Uttarakhand" },
  { value: "27", name: "Uttar Pradesh" },
  { value: "28", name: "West Bengal" },
];

const Cities = {
  "Andhra Pradesh": [
    { value: "1", name: "Visakhapatnam" },
    { value: "2", name: "Vijayawada" },
    { value: "3", name: "Guntur" },
    { value: "4", name: "Nellore" },
    { value: "5", name: "Kurnool" },
    { value: "6", name: "Rajahmundry" },
    { value: "7", name: "Tirupati" },
  ],
  "Arunachal Pradesh": [
    { value: "1", name: "Itanagar" },
    { value: "2", name: "Naharlagun" },
  ],
  Assam: [
    { value: "1", name: "Guwahati" },
    { value: "2", name: "Silchar" },
    { value: "3", name: "Dibrugarh" },
    { value: "4", name: "Jorhat" },
    { value: "5", name: "Nagaon" },
    { value: "6", name: "Tinsukia" },
    { value: "7", name: "Tezpur" },
  ],
  Bihar: [
    { value: "1", name: "Patna" },
    { value: "2", name: "Gaya" },
    { value: "3", name: "Bhagalpur" },
    { value: "4", name: "Muzaffarpur" },
    { value: "5", name: "Darbhanga" },
    { value: "6", name: "Arrah" },
    { value: "7", name: "Bihar Sharif" },
  ],
  Chhattisgarh: [
    { value: "1", name: "Raipur" },
    { value: "2", name: "Bhilai" },
    { value: "3", name: "Bilaspur" },
    { value: "4", name: "Korba" },
    { value: "5", name: "Durg" },
    { value: "6", name: "Rajnandgaon" },
    { value: "7", name: "Raigarh" },
  ],
  Goa: [
    { value: "1", name: "Panaji" },
    { value: "2", name: "Margao" },
    { value: "3", name: "Vasco da Gama" },
    { value: "4", name: "Mapusa" },
    { value: "5", name: "Ponda" },
    { value: "6", name: "Bicholim" },
    { value: "7", name: "Curchorem" },
  ],
  Gujarat: [
    { value: "1", name: "Ahmedabad" },
    { value: "2", name: "Surat" },
    { value: "3", name: "Vadodara" },
    { value: "4", name: "Rajkot" },
    { value: "5", name: "Bhavnagar" },
    { value: "6", name: "Jamnagar" },
    { value: "7", name: "Junagadh" },
  ],
  Haryana: [
    { value: "1", name: "Faridabad" },
    { value: "2", name: "Gurgaon" },
    { value: "3", name: "Panipat" },
    { value: "4", name: "Ambala" },
    { value: "5", name: "Rohtak" },
    { value: "6", name: "Hisar" },
    { value: "7", name: "Karnal" },
  ],
  "Himachal Pradesh": [
    { value: "1", name: "Shimla" },
    { value: "2", name: "Solan" },
    { value: "3", name: "Dharamsala" },
    { value: "4", name: "Kangra" },
    { value: "5", name: "Mandi" },
    { value: "6", name: "Una" },
    { value: "7", name: "Kullu" },
  ],
  Jharkhand: [
    { value: "1", name: "Ranchi" },
    { value: "2", name: "Jamshedpur" },
    { value: "3", name: "Dhanbad" },
    { value: "4", name: "Bokaro Steel City" },
    { value: "5", name: "Deoghar" },
    { value: "6", name: "Phusro" },
    { value: "7", name: "Hazaribagh" },
  ],
  Karnataka: [
    { value: "1", name: "Bangalore" },
    { value: "2", name: "Mysore" },
    { value: "3", name: "Hubli-Dharwad" },
    { value: "4", name: "Mangalore" },
    { value: "5", name: "Belgaum" },
    { value: "6", name: "Gulbarga" },
    { value: "7", name: "Davanagere" },
  ],
  Kerala: [
    { value: "1", name: "Thiruvananthapuram" },
    { value: "2", name: "Kochi" },
    { value: "3", name: "Kozhikode" },
    { value: "4", name: "Thrissur" },
    { value: "5", name: "Kollam" },
    { value: "6", name: "Palakkad" },
    { value: "7", name: "Alappuzha" },
  ],
  "Madhya Pradesh": [
    { value: "1", name: "Indore" },
    { value: "2", name: "Bhopal" },
    { value: "3", name: "Jabalpur" },
    { value: "4", name: "Gwalior" },
    { value: "5", name: "Ujjain" },
    { value: "6", name: "Sagar" },
    { value: "7", name: "Dewas" },
  ],
  Maharashtra: [
    { value: "1", name: "Mumbai" },
    { value: "2", name: "Pune" },
    { value: "3", name: "Nagpur" },
    { value: "4", name: "Nashik" },
    { value: "5", name: "Thane" },
    { value: "6", name: "Aurangabad" },
    { value: "7", name: "Solapur" },
  ],
  Manipur: [{ value: "1", name: "Imphal" }],
  Meghalaya: [
    { value: "1", name: "Shillong" },
    { value: "2", name: "Tura" },
    { value: "3", name: "Nongstoin" },
  ],
  Mizoram: [{ value: "1", name: "Aizawl" }],
  Nagaland: [
    { value: "1", name: "Kohima" },
    { value: "2", name: "Dimapur" },
  ],
  Odisha: [
    { value: "1", name: "Bhubaneswar" },
    { value: "2", name: "Cuttack" },
    { value: "3", name: "Rourkela" },
    { value: "4", name: "Brahmapur" },
    { value: "5", name: "Sambalpur" },
    { value: "6", name: "Puri" },
    { value: "7", name: "Balasore" },
  ],
  Punjab: [
    { value: "1", name: "Ludhiana" },
    { value: "2", name: "Amritsar" },
    { value: "3", name: "Jalandhar" },
    { value: "4", name: "Patiala" },
    { value: "5", name: "Bathinda" },
    { value: "6", name: "Hoshiarpur" },
    { value: "7", name: "Mohali" },
  ],
  Rajasthan: [
    { value: "1", name: "Jaipur" },
    { value: "2", name: "Jodhpur" },
    { value: "3", name: "Kota" },
    { value: "4", name: "Bikaner" },
    { value: "5", name: "Ajmer" },
    { value: "6", name: "Udaipur" },
    { value: "7", name: "Bhilwara" },
  ],
  Sikkim: [{ value: "1", name: "Gangtok" }],
  "Tamil Nadu": [
    { value: "1", name: "Chennai" },
    { value: "2", name: "Coimbatore" },
    { value: "3", name: "Madurai" },
    { value: "4", name: "Tiruchirappalli" },
    { value: "5", name: "Salem" },
    { value: "6", name: "Tirunelveli" },
    { value: "7", name: "Tiruppur" },
  ],
  Telangana: [
    { value: "1", name: "Hyderabad" },
    { value: "2", name: "Warangal" },
    { value: "3", name: "Nizamabad" },
    { value: "4", name: "Karimnagar" },
    { value: "5", name: "Ramagundam" },
    { value: "6", name: "Khammam" },
    { value: "7", name: "Mahbubnagar" },
  ],
  Tripura: [{ value: "1", name: "Agartala" }],
  "Uttar Pradesh": [
    { value: "1", name: "Lucknow" },
    { value: "2", name: "Kanpur" },
    { value: "3", name: "Ghaziabad" },
    { value: "4", name: "Agra" },
    { value: "5", name: "Varanasi" },
    { value: "6", name: "Allahabad" },
    { value: "7", name: "Meerut" },
  ],
  Uttarakhand: [
    { value: "1", name: "Dehradun" },
    { value: "2", name: "Haridwar" },
    { value: "3", name: "Roorkee" },
    { value: "4", name: "Haldwani" },
    { value: "5", name: "Rudrapur" },
    { value: "6", name: "Kashipur" },
    { value: "7", name: "Rishikesh" },
  ],
  "West Bengal": [
    { value: "1", name: "Kolkata" },
    { value: "2", name: "Asansol" },
    { value: "3", name: "Siliguri" },
    { value: "4", name: "Durgapur" },
    { value: "5", name: "Bardhaman" },
    { value: "6", name: "English Bazar" },
    { value: "7", name: "Baharampur" },
  ],
};

const DeptList = [
  { value: "1", name: "Ward A", url: MRD2 },
  { value: "2", name: "Ward B", url: MUD },
  {
    value: "3",
    name: "Ward C",
    url: MEN1,
  },
  { value: "4", name: "Ward D", url: MWS },
  { value: "5", name: "Ward E", url: CWC },
  { value: "6", name: "Ward F north", url: CGWB },
  { value: "7", name: "Ward F south", url: CPCB },
  {
    value: "8",
    name: "Ward G north ",
    url: NDMA,
  },
  { value: "9", name: "Ward G south", url: MHA },
  { value: "10", name: "Ward H east", url: NDRF },
  { value: "11", name: "Ward H west", url: NDRF },
  { value: "12", name: "Ward K east", url: NDRF },
  { value: "13", name: "Ward K west", url: NDRF },
  { value: "14", name: "Ward M east", url: NDRF },
  { value: "15", name: "Ward M west ", url: NDRF },
  { value: "16", name: "Ward L", url: NDRF },
  { value: "17", name: "Ward T", url: NDRF },
  { value: "18", name: "Ward N", url: NDRF },
];

export { Departments, States, DeptList, Cities };
